/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatFooter {
    }
    interface ChatHeader {
    }
    interface ChatPane {
    }
    interface ChatPaneOld {
    }
    interface MyCounter {
    }
    interface NewChatPane {
    }
}
declare global {
    interface HTMLChatFooterElement extends Components.ChatFooter, HTMLStencilElement {
    }
    var HTMLChatFooterElement: {
        prototype: HTMLChatFooterElement;
        new (): HTMLChatFooterElement;
    };
    interface HTMLChatHeaderElement extends Components.ChatHeader, HTMLStencilElement {
    }
    var HTMLChatHeaderElement: {
        prototype: HTMLChatHeaderElement;
        new (): HTMLChatHeaderElement;
    };
    interface HTMLChatPaneElement extends Components.ChatPane, HTMLStencilElement {
    }
    var HTMLChatPaneElement: {
        prototype: HTMLChatPaneElement;
        new (): HTMLChatPaneElement;
    };
    interface HTMLChatPaneOldElement extends Components.ChatPaneOld, HTMLStencilElement {
    }
    var HTMLChatPaneOldElement: {
        prototype: HTMLChatPaneOldElement;
        new (): HTMLChatPaneOldElement;
    };
    interface HTMLMyCounterElement extends Components.MyCounter, HTMLStencilElement {
    }
    var HTMLMyCounterElement: {
        prototype: HTMLMyCounterElement;
        new (): HTMLMyCounterElement;
    };
    interface HTMLNewChatPaneElement extends Components.NewChatPane, HTMLStencilElement {
    }
    var HTMLNewChatPaneElement: {
        prototype: HTMLNewChatPaneElement;
        new (): HTMLNewChatPaneElement;
    };
    interface HTMLElementTagNameMap {
        "chat-footer": HTMLChatFooterElement;
        "chat-header": HTMLChatHeaderElement;
        "chat-pane": HTMLChatPaneElement;
        "chat-pane-old": HTMLChatPaneOldElement;
        "my-counter": HTMLMyCounterElement;
        "new-chat-pane": HTMLNewChatPaneElement;
    }
}
declare namespace LocalJSX {
    interface ChatFooter {
    }
    interface ChatHeader {
    }
    interface ChatPane {
    }
    interface ChatPaneOld {
    }
    interface MyCounter {
    }
    interface NewChatPane {
    }
    interface IntrinsicElements {
        "chat-footer": ChatFooter;
        "chat-header": ChatHeader;
        "chat-pane": ChatPane;
        "chat-pane-old": ChatPaneOld;
        "my-counter": MyCounter;
        "new-chat-pane": NewChatPane;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-footer": LocalJSX.ChatFooter & JSXBase.HTMLAttributes<HTMLChatFooterElement>;
            "chat-header": LocalJSX.ChatHeader & JSXBase.HTMLAttributes<HTMLChatHeaderElement>;
            "chat-pane": LocalJSX.ChatPane & JSXBase.HTMLAttributes<HTMLChatPaneElement>;
            "chat-pane-old": LocalJSX.ChatPaneOld & JSXBase.HTMLAttributes<HTMLChatPaneOldElement>;
            "my-counter": LocalJSX.MyCounter & JSXBase.HTMLAttributes<HTMLMyCounterElement>;
            "new-chat-pane": LocalJSX.NewChatPane & JSXBase.HTMLAttributes<HTMLNewChatPaneElement>;
        }
    }
}
